package com.dashnex.d1.jdbc;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executor;

/** A connection to one D1 database. Stateless over HTTP; always auto-commit. */
public class D1Connection implements Connection {
    private final D1ConnectionConfig config;
    private final D1Client client;
    private final Map<String, Map<String, String>> declaredTypesCache = new ConcurrentHashMap<>();
    private final Properties clientInfo = new Properties();
    private volatile boolean closed;
    private boolean autoCommit = true;
    private boolean readOnly;
    private SQLWarning warnings;
    private int networkTimeoutMillis;

    public D1Connection(D1ConnectionConfig config, D1Client client) {
        this.config = config;
        this.client = client;
    }

    D1Client client() { return client; }
    D1ConnectionConfig config() { return config; }

    /** Declared column types of a table keyed by lower-case column name; empty if unknown. Cached — but only
     * on success, so a transient failure (e.g. a network blip) is retried on the next call instead of being
     * remembered forever as "this table has no columns". */
    Map<String, String> declaredTypes(String table) {
        Map<String, String> cached = declaredTypesCache.computeIfAbsent(table.toLowerCase(Locale.ROOT), key -> {
            try {
                List<D1Result> results = client.execute("SELECT name, type FROM pragma_table_info(?)", List.of(table));
                Map<String, String> types = new HashMap<>();
                if (!results.isEmpty()) {
                    for (Object[] row : results.get(results.size() - 1).getRows()) {
                        types.put(String.valueOf(row[0]).toLowerCase(Locale.ROOT), row[1] == null ? "" : String.valueOf(row[1]));
                    }
                }
                return types;
            } catch (SQLException e) {
                return null; // do not cache a failed lookup
            }
        });
        return cached == null ? Map.of() : cached;
    }

    void schemaChanged() {
        declaredTypesCache.clear();
    }

    void checkOpen() throws SQLException {
        if (closed) throw new SQLException("Connection is closed", "08003");
    }

    private void addWarning(SQLWarning w) {
        if (warnings == null) warnings = w;
        else warnings.setNextWarning(w);
    }

    private static SQLFeatureNotSupportedException unsupported(String what) {
        return new SQLFeatureNotSupportedException(what + " is not supported by Cloudflare D1");
    }

    @Override public Statement createStatement() throws SQLException { checkOpen(); return new D1Statement(this); }
    @Override public Statement createStatement(int t, int c) throws SQLException { return createStatement(); }
    @Override public Statement createStatement(int t, int c, int h) throws SQLException { return createStatement(); }
    @Override public PreparedStatement prepareStatement(String sql) throws SQLException { checkOpen(); return new D1PreparedStatement(this, sql); }
    @Override public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException { return prepareStatement(sql); }
    @Override public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException { return prepareStatement(sql); }
    @Override public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException { return prepareStatement(sql); }
    @Override public PreparedStatement prepareStatement(String sql, int t, int c) throws SQLException { return prepareStatement(sql); }
    @Override public PreparedStatement prepareStatement(String sql, int t, int c, int h) throws SQLException { return prepareStatement(sql); }
    @Override public CallableStatement prepareCall(String sql) throws SQLException { throw unsupported("Stored procedures"); }
    @Override public CallableStatement prepareCall(String sql, int t, int c) throws SQLException { throw unsupported("Stored procedures"); }
    @Override public CallableStatement prepareCall(String sql, int t, int c, int h) throws SQLException { throw unsupported("Stored procedures"); }
    @Override public String nativeSQL(String sql) { return sql; }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        checkOpen();
        if (!autoCommit && this.autoCommit) {
            addWarning(new SQLWarning("Cloudflare D1 has no interactive transactions: every statement is committed "
                    + "immediately; commit() and rollback() do nothing"));
        }
        this.autoCommit = autoCommit;
    }

    @Override public boolean getAutoCommit() throws SQLException { checkOpen(); return autoCommit; }
    @Override public void commit() throws SQLException { checkOpen(); }
    @Override public void rollback() throws SQLException { checkOpen(); }
    @Override public void rollback(Savepoint savepoint) throws SQLException { throw unsupported("Savepoints"); }
    @Override public Savepoint setSavepoint() throws SQLException { throw unsupported("Savepoints"); }
    @Override public Savepoint setSavepoint(String name) throws SQLException { throw unsupported("Savepoints"); }
    @Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { throw unsupported("Savepoints"); }
    @Override public void close() { closed = true; }
    @Override public boolean isClosed() { return closed; }
    @Override public DatabaseMetaData getMetaData() throws SQLException { checkOpen(); return new D1DatabaseMetaData(this); }
    @Override public void setReadOnly(boolean readOnly) { this.readOnly = readOnly; }
    @Override public boolean isReadOnly() { return readOnly; }
    @Override public void setCatalog(String catalog) { }
    @Override public String getCatalog() { return null; }
    @Override public void setTransactionIsolation(int level) { }
    @Override public int getTransactionIsolation() { return TRANSACTION_NONE; }
    @Override public SQLWarning getWarnings() { return warnings; }
    @Override public void clearWarnings() { warnings = null; }
    @Override public Map<String, Class<?>> getTypeMap() { return new HashMap<>(); }
    @Override public void setTypeMap(Map<String, Class<?>> map) { }
    @Override public void setHoldability(int holdability) { }
    @Override public int getHoldability() { return ResultSet.CLOSE_CURSORS_AT_COMMIT; }
    @Override public Clob createClob() throws SQLException { throw unsupported("Clob"); }
    @Override public Blob createBlob() throws SQLException { throw unsupported("Blob"); }
    @Override public NClob createNClob() throws SQLException { throw unsupported("NClob"); }
    @Override public SQLXML createSQLXML() throws SQLException { throw unsupported("SQLXML"); }

    @Override
    public boolean isValid(int timeout) {
        if (closed) return false;
        try {
            client.ping(timeout > 0 ? timeout : config.getTimeoutSeconds());
            return true;
        } catch (SQLException e) {
            return false;
        }
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        if (value == null) clientInfo.remove(name);
        else clientInfo.setProperty(name, value);
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        clientInfo.clear();
        if (properties != null) clientInfo.putAll(properties);
    }

    @Override public String getClientInfo(String name) { return clientInfo.getProperty(name); }

    @Override
    public Properties getClientInfo() {
        Properties copy = new Properties();
        copy.putAll(clientInfo);
        return copy;
    }

    @Override public Array createArrayOf(String typeName, Object[] elements) throws SQLException { throw unsupported("Arrays"); }
    @Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { throw unsupported("Structs"); }
    @Override public void setSchema(String schema) { }
    @Override public String getSchema() { return null; }
    @Override public void abort(Executor executor) { closed = true; }
    @Override public void setNetworkTimeout(Executor executor, int milliseconds) { networkTimeoutMillis = milliseconds; }
    @Override public int getNetworkTimeout() { return networkTimeoutMillis; }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("Not a wrapper for " + iface.getName());
    }

    @Override public boolean isWrapperFor(Class<?> iface) { return iface.isInstance(this); }
}
