package com.dashnex.d1.jdbc;

import java.sql.BatchUpdateException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.List;
import java.util.Map;

/** Statement backed by one D1 HTTP call per execution (or per batch). */
public class D1Statement implements Statement {
    protected final D1Connection connection;
    private final List<D1Client.Stmt> batch = new ArrayList<>();
    private final Deque<D1Result> pendingResults = new ArrayDeque<>();
    private D1ResultSet currentResultSet;
    private int updateCount = -1;
    private long generatedKey = -1;
    private String lastSql;
    private boolean closed;
    private int maxRows;
    private int queryTimeout;
    private int fetchSize;
    private boolean poolable;
    private boolean closeOnCompletion;
    private SQLWarning warnings;

    D1Statement(D1Connection connection) {
        this.connection = connection;
    }

    protected void checkOpen() throws SQLException {
        if (closed) throw new SQLException("Statement is closed", "HY010");
        connection.checkOpen();
    }

    private void addWarning(SQLWarning w) {
        if (warnings == null) warnings = w;
        else warnings.setNextWarning(w);
    }

    private void closeCurrentResultSet() {
        if (currentResultSet != null) {
            currentResultSet.closeSilently();
            currentResultSet = null;
        }
    }

    protected boolean executeInternal(String sql, List<Object> params) throws SQLException {
        checkOpen();
        closeCurrentResultSet();
        pendingResults.clear();
        generatedKey = -1;
        lastSql = sql;
        if (SqlText.isTransactionControl(sql)) {
            addWarning(new SQLWarning("Ignored '" + sql.trim() + "': Cloudflare D1 has no interactive transactions"));
            updateCount = 0;
            return false;
        }
        String rewritten = SqlText.rewrite(sql);
        String sent = maxRows > 0 && SqlText.isSelect(sql)
                ? "SELECT * FROM (" + SqlText.stripTrailingSemicolons(rewritten) + ") LIMIT " + maxRows
                : rewritten;
        List<D1Result> results = connection.client().execute(sent, params);
        if (SqlText.isDdl(sql)) {
            connection.schemaChanged();
        }
        if (SqlText.isInsert(sql) && !results.isEmpty()) {
            D1Result last = results.get(results.size() - 1);
            if (last.getChanges() > 0) generatedKey = last.getLastRowId();
        }
        pendingResults.addAll(results);
        return nextResult();
    }

    private boolean nextResult() {
        D1Result r = pendingResults.poll();
        if (r == null) {
            currentResultSet = null;
            updateCount = -1;
            return false;
        }
        if (r.hasColumns()) {
            String table = SqlText.singleTable(lastSql);
            Map<String, String> declared = table == null ? null : connection.declaredTypes(table);
            currentResultSet = D1ResultSet.forQuery(this, r, maxRows, table, declared);
            updateCount = -1;
            return true;
        }
        currentResultSet = null;
        updateCount = (int) Math.min(Integer.MAX_VALUE, r.getChanges());
        return false;
    }

    protected void addToBatch(D1Client.Stmt stmt) throws SQLException {
        checkOpen();
        batch.add(stmt);
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        if (!executeInternal(sql, List.of())) {
            throw new SQLException("Statement did not return a result set", "02000");
        }
        return currentResultSet;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        executeInternal(sql, List.of());
        return Math.max(updateCount, 0);
    }

    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override public long executeLargeUpdate(String sql) throws SQLException { return executeUpdate(sql); }
    @Override public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override public boolean execute(String sql) throws SQLException { return executeInternal(sql, List.of()); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }
    @Override public ResultSet getResultSet() throws SQLException { checkOpen(); return currentResultSet; }
    @Override public int getUpdateCount() throws SQLException { checkOpen(); return updateCount; }
    @Override public long getLargeUpdateCount() throws SQLException { return getUpdateCount(); }

    @Override
    public boolean getMoreResults() throws SQLException {
        checkOpen();
        closeCurrentResultSet();
        return nextResult();
    }

    @Override public boolean getMoreResults(int current) throws SQLException { return getMoreResults(); }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        checkOpen();
        List<Object[]> rows = new ArrayList<>();
        if (generatedKey > 0) rows.add(new Object[]{generatedKey});
        return D1ResultSet.of(this, new String[]{"last_insert_rowid()"}, new int[]{Types.BIGINT}, rows);
    }

    @Override public void addBatch(String sql) throws SQLException { addToBatch(new D1Client.Stmt(sql, List.of())); }
    @Override public void clearBatch() { batch.clear(); }

    @Override
    public int[] executeBatch() throws SQLException {
        checkOpen();
        closeCurrentResultSet();
        List<D1Client.Stmt> toRun = new ArrayList<>(batch);
        batch.clear();
        int[] counts = new int[toRun.size()];
        List<D1Client.Stmt> sent = new ArrayList<>();
        List<Integer> sentIndex = new ArrayList<>();
        for (int i = 0; i < toRun.size(); i++) {
            D1Client.Stmt s = toRun.get(i);
            if (SqlText.isTransactionControl(s.getSql())) {
                counts[i] = SUCCESS_NO_INFO;
                continue;
            }
            sent.add(new D1Client.Stmt(SqlText.rewrite(s.getSql()), s.getParams()));
            sentIndex.add(i);
        }
        if (sent.isEmpty()) return counts;
        List<D1Result> results;
        try {
            results = connection.client().batch(sent);
        } catch (SQLException e) {
            throw new BatchUpdateException(e.getMessage(), e.getSQLState(), e.getErrorCode(), new int[0], e);
        }
        boolean aligned = results.size() == sent.size();
        generatedKey = -1;
        for (int j = 0; j < sent.size(); j++) {
            int i = sentIndex.get(j);
            if (!aligned) {
                counts[i] = SUCCESS_NO_INFO;
                continue;
            }
            D1Result r = results.get(j);
            counts[i] = (int) Math.min(Integer.MAX_VALUE, r.getChanges());
            if (SqlText.isInsert(sent.get(j).getSql()) && r.getChanges() > 0) generatedKey = r.getLastRowId();
        }
        for (D1Client.Stmt s : sent) {
            if (SqlText.isDdl(s.getSql())) {
                connection.schemaChanged();
                break;
            }
        }
        return counts;
    }

    @Override public long[] executeLargeBatch() throws SQLException {
        int[] counts = executeBatch();
        long[] out = new long[counts.length];
        for (int i = 0; i < counts.length; i++) out[i] = counts[i];
        return out;
    }

    @Override public void close() { closeCurrentResultSet(); closed = true; }
    @Override public boolean isClosed() { return closed; }
    @Override public int getMaxFieldSize() { return 0; }
    @Override public void setMaxFieldSize(int max) { }
    @Override public int getMaxRows() { return maxRows; }
    @Override public void setMaxRows(int max) { maxRows = Math.max(0, max); }
    @Override public void setEscapeProcessing(boolean enable) { }
    @Override public int getQueryTimeout() { return queryTimeout; }
    @Override public void setQueryTimeout(int seconds) { queryTimeout = seconds; }
    @Override public void cancel() { }
    @Override public SQLWarning getWarnings() { return warnings; }
    @Override public void clearWarnings() { warnings = null; }
    @Override public void setCursorName(String name) { }
    @Override public void setFetchDirection(int direction) { }
    @Override public int getFetchDirection() { return ResultSet.FETCH_FORWARD; }
    @Override public void setFetchSize(int rows) { fetchSize = rows; }
    @Override public int getFetchSize() { return fetchSize; }
    @Override public int getResultSetConcurrency() { return ResultSet.CONCUR_READ_ONLY; }
    @Override public int getResultSetType() { return ResultSet.TYPE_SCROLL_INSENSITIVE; }
    @Override public Connection getConnection() { return connection; }
    @Override public int getResultSetHoldability() { return ResultSet.CLOSE_CURSORS_AT_COMMIT; }
    @Override public void setPoolable(boolean poolable) { this.poolable = poolable; }
    @Override public boolean isPoolable() { return poolable; }
    @Override public void closeOnCompletion() { closeOnCompletion = true; }
    @Override public boolean isCloseOnCompletion() { return closeOnCompletion; }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("Not a wrapper for " + iface.getName());
    }

    @Override public boolean isWrapperFor(Class<?> iface) { return iface.isInstance(this); }
}
